eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: EVENT-SERVICE
          uri: lb://EVENT-SERVICE
          predicates:
            - Path=/api/events/**
          filters:
            - StripPrefix=1
