services:
  # Eureka Discovery Server
  discovery-server:
    build:
      context: ./discovery-server
      dockerfile: Dockerfile
    container_name: discovery-server
    hostname: discovery-server
    ports:
      - "8761:8761"
    networks:
      - easy-tickets-network
    depends_on:
      - oracle-db
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_INSTANCE_HOSTNAME=discovery-server
    restart: unless-stopped

  # API Gateway
  api-gateway:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8081:8081"
    depends_on:
      - discovery-server
    networks:
      - easy-tickets-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    restart: unless-stopped

  # Event Service
  event-service:
    build:
      context: ./event-service
      dockerfile: Dockerfile
    container_name: event-service
    ports:
      - "8082:8082"
    depends_on:
      - discovery-server
      - oracle-db
    networks:
      - easy-tickets-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle-db:1521/freepdb1
      - SPRING_DATASOURCE_USERNAME=EVENT_SERVICE
      - SPRING_DATASOURCE_PASSWORD=root
    restart: unless-stopped

  # Oracle Database
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-db
    environment:
      - ORACLE_DATABASE=freepdb1
      - APP_USER=event_service
      - APP_USER_PASSWORD=root
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata
    networks:
      - easy-tickets-network
    restart: unless-stopped

networks:
  easy-tickets-network:
    driver: bridge

volumes:
  oracle-data:
