spring:
  application:
    name: DISCOVERY-SERVER
server:
  port: 8080
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
  instance:
    hostname: discovery-server
